@AgroScan.WebAPI_HostAddress = http://localhost:5298

GET {{AgroScan.WebAPI_HostAddress}}/api/v1/Plants
Accept: application/json
Authorization: Bearer CfDJ8BsTcJBYJFxAuy9KX1jWhciGUPx2SqqhHcdnMPJay7q-kzORk0C6JamV2DeELDNW57WQ8fmQ2QzRUHIc2sJe5IDrNmWLetfBp77KcoYQkjIjDfGnTdeoW3HyoE-SKLaf51RKBLqITs4dzlbcf8uMGDBchNJEwWqIrWltniX2MvWMli-L8Tx3_gfNZw2HdvPg0cAQY8klCqD0aHQd7aUGpJzzUX5L1YciKxR4RxevDwallqeiJSpyCD_tiRsif6LcqdjZs9VNDQ8smJOlxQyyqYt6qy1_zagzD6kZ2ZtxKp75qSEQGBgxSb32LybGyZdCuokqsRZcDbS_tK2wQ4BdgO2xS6ExHyxQjlDuZ8E3lBYkzVbjBGLkvxoKNfU_msYRo0uEAddGiAjQFnn9Fi6sikUTQ9830d4zz1BVxDR_6UkJDokGim7-p9qVZp0v0eA4p4UODA8frFUyDHqmMJJTNygrwTija6iX0khKG8aNQ5bwi3Nase7RMqGWJT-fuHUCkR4LlAZO0zBkTgks6qVcwFrrKjyNJ3oOsQsEZyk7kUM0zER7Mdc7m1t8NU992Pnq4aNy2QYnUOkRvN8wBy4yEHZzVUIEWkBZrrZOMaE8aEZhaB05-0dBNRL4KGSmSg5JtdhWsBTtDr_aJu3psvxOqbQHoWotSl3uPjotJDymr3d_F4ZEHnDe0HAgJtjH8IdnaQ
###
