import os
import random
import shutil

def move_random_images(source_dir, destination_dir, num_images):
    # Get a list of all files in the source directory
    all_files = os.listdir(source_dir)

    # Randomly select 'num_images' files
    selected_files = random.sample(all_files, num_images)

    # Create the destination directory if it doesn't exist
    os.makedirs(destination_dir, exist_ok=True)

    # Move selected files to the destination directory
    for file_name in selected_files:
        source_path = os.path.join(source_dir, file_name)
        destination_path = os.path.join(destination_dir, file_name)
        shutil.move(source_path, destination_path)


# config
source_directory = '../dataset/all'

destination_train_directory = '../dataset/train_new'
destination_validation_directory = '../dataset/validation_new'
destination_test_directory = '../dataset/test_new'

num_images_to_move_to_train = 550
num_images_to_move_to_validation = 330
num_images_to_move_to_test = 220


source_directory_bacterial_spot = source_directory + '/Tomato___Bacterial_spot'
source_directory_early_blight = source_directory + '/Tomato___Early_blight'
source_directory_healthy = source_directory + '/Tomato___healthy'
source_directory_late_blight = source_directory + '/Tomato___Late_blight'
source_directory_leaf_mold = source_directory + '/Tomato___Leaf_Mold'
source_directory_septoria_leaf_spot = source_directory + '/Tomato___Septoria_leaf_spot'
source_directory_spider_mites = source_directory + '/Tomato___Spider_mites Two-spotted_spider_mite'
source_directory_target_spot = source_directory + '/Tomato___Target_Spot'
source_directory_mosaic_virus = source_directory + '/Tomato___Tomato_mosaic_virus'
source_directory_yellow_leaf_curl_virus = source_directory + '/Tomato___Tomato_Yellow_Leaf_Curl_Virus'

destination_train_directory_bacterial_spot = destination_train_directory + '/Tomato___Bacterial_spot'
destination_train_directory_early_blight = destination_train_directory + '/Tomato___Early_blight'
destination_train_directory_healthy = destination_train_directory + '/Tomato___healthy'
destination_train_directory_late_blight = destination_train_directory + '/Tomato___Late_blight'
destination_train_directory_leaf_mold = destination_train_directory + '/Tomato___Leaf_Mold'
destination_train_directory_septoria_leaf_spot = destination_train_directory + '/Tomato___Septoria_leaf_spot'
destination_train_directory_spider_mites = destination_train_directory + '/Tomato___Spider_mites Two-spotted_spider_mite'
destination_train_directory_target_spot = destination_train_directory + '/Tomato___Target_Spot'
destination_train_directory_mosaic_virus = destination_train_directory + '/Tomato___Tomato_mosaic_virus'
destination_train_directory_yellow_leaf_curl_virus = destination_train_directory + '/Tomato___Tomato_Yellow_Leaf_Curl_Virus'

destination_validation_directory_bacterial_spot = destination_validation_directory + '/Tomato___Bacterial_spot'
destination_validation_directory_early_blight = destination_validation_directory + '/Tomato___Early_blight'
destination_validation_directory_healthy = destination_validation_directory + '/Tomato___healthy'
destination_validation_directory_late_blight = destination_validation_directory + '/Tomato___Late_blight'
destination_validation_directory_leaf_mold = destination_validation_directory + '/Tomato___Leaf_Mold'
destination_validation_directory_septoria_leaf_spot = destination_validation_directory + '/Tomato___Septoria_leaf_spot'
destination_validation_directory_spider_mites = destination_validation_directory + '/Tomato___Spider_mites Two-spotted_spider_mite'
destination_validation_directory_target_spot = destination_validation_directory + '/Tomato___Target_Spot'
destination_validation_directory_mosaic_virus = destination_validation_directory + '/Tomato___Tomato_mosaic_virus'
destination_validation_directory_yellow_leaf_curl_virus = destination_validation_directory + '/Tomato___Tomato_Yellow_Leaf_Curl_Virus'

destination_test_directory_bacterial_spot = destination_test_directory + '/Tomato___Bacterial_spot'
destination_test_directory_early_blight = destination_test_directory + '/Tomato___Early_blight'
destination_test_directory_healthy = destination_test_directory + '/Tomato___healthy'
destination_test_directory_late_blight = destination_test_directory + '/Tomato___Late_blight'
destination_test_directory_leaf_mold = destination_test_directory + '/Tomato___Leaf_Mold'
destination_test_directory_septoria_leaf_spot = destination_test_directory + '/Tomato___Septoria_leaf_spot'
destination_test_directory_spider_mites = destination_test_directory + '/Tomato___Spider_mites Two-spotted_spider_mite'
destination_test_directory_target_spot = destination_test_directory + '/Tomato___Target_Spot'
destination_test_directory_mosaic_virus = destination_test_directory + '/Tomato___Tomato_mosaic_virus'
destination_test_directory_yellow_leaf_curl_virus = destination_test_directory + '/Tomato___Tomato_Yellow_Leaf_Curl_Virus'

move_random_images(source_directory_bacterial_spot, destination_train_directory_bacterial_spot, num_images_to_move_to_train)
move_random_images(source_directory_early_blight, destination_train_directory_early_blight, num_images_to_move_to_train)
move_random_images(source_directory_healthy, destination_train_directory_healthy, num_images_to_move_to_train)
move_random_images(source_directory_late_blight, destination_train_directory_late_blight, num_images_to_move_to_train)
move_random_images(source_directory_leaf_mold, destination_train_directory_leaf_mold, num_images_to_move_to_train)
move_random_images(source_directory_septoria_leaf_spot, destination_train_directory_septoria_leaf_spot, num_images_to_move_to_train)
move_random_images(source_directory_spider_mites, destination_train_directory_spider_mites, num_images_to_move_to_train)
move_random_images(source_directory_target_spot, destination_train_directory_target_spot, num_images_to_move_to_train)
move_random_images(source_directory_mosaic_virus, destination_train_directory_mosaic_virus, num_images_to_move_to_train)
move_random_images(source_directory_yellow_leaf_curl_virus, destination_train_directory_yellow_leaf_curl_virus, num_images_to_move_to_train)

move_random_images(source_directory_bacterial_spot, destination_validation_directory_bacterial_spot, num_images_to_move_to_validation)
move_random_images(source_directory_early_blight, destination_validation_directory_early_blight, num_images_to_move_to_validation)
move_random_images(source_directory_healthy, destination_validation_directory_healthy, num_images_to_move_to_validation)
move_random_images(source_directory_late_blight, destination_validation_directory_late_blight, num_images_to_move_to_validation)
move_random_images(source_directory_leaf_mold, destination_validation_directory_leaf_mold, num_images_to_move_to_validation)
move_random_images(source_directory_septoria_leaf_spot, destination_validation_directory_septoria_leaf_spot, num_images_to_move_to_validation)
move_random_images(source_directory_spider_mites, destination_validation_directory_spider_mites, num_images_to_move_to_validation)
move_random_images(source_directory_target_spot, destination_validation_directory_target_spot, num_images_to_move_to_validation)
move_random_images(source_directory_mosaic_virus, destination_validation_directory_mosaic_virus, num_images_to_move_to_validation)
move_random_images(source_directory_yellow_leaf_curl_virus, destination_validation_directory_yellow_leaf_curl_virus, num_images_to_move_to_validation)

move_random_images(source_directory_bacterial_spot, destination_test_directory_bacterial_spot, num_images_to_move_to_test)
move_random_images(source_directory_early_blight, destination_test_directory_early_blight, num_images_to_move_to_test)
move_random_images(source_directory_healthy, destination_test_directory_healthy, num_images_to_move_to_test)
move_random_images(source_directory_late_blight, destination_test_directory_late_blight, num_images_to_move_to_test)
move_random_images(source_directory_leaf_mold, destination_test_directory_leaf_mold, num_images_to_move_to_test)
move_random_images(source_directory_septoria_leaf_spot, destination_test_directory_septoria_leaf_spot, num_images_to_move_to_test)
move_random_images(source_directory_spider_mites, destination_test_directory_spider_mites, num_images_to_move_to_test)
move_random_images(source_directory_target_spot, destination_test_directory_target_spot, num_images_to_move_to_test)
move_random_images(source_directory_mosaic_virus, destination_test_directory_mosaic_virus, num_images_to_move_to_test)
move_random_images(source_directory_yellow_leaf_curl_virus, destination_test_directory_yellow_leaf_curl_virus, num_images_to_move_to_test)